### ISSUE TITLE
cd command misbehaving

### ISSUE THREAD

**Issue by rohanchidrewar05** [rohanchidrewar05/py-shell#1]
When using cd to enter files which have '-' in the name, the command misinterprets it as an option and misbehaves.

**Comment by mackenzieros** [comment]
Hi, I'd like to help you with this issue!

**Comment by rohanchidrewar05** [comment]
Sure, take a look at the code and make changes.

**Comment by rohanchidrewar05** [comment]
Closing the issue, as debugging the pre_process_cmd function resolved the issue.
